export default {
  mainBlue: "#0B40FF",
  mainPink: "#FF9CE1",
  sDarkBlue: "#03237C",
  nWhite: "white",
  nMediumGrey: "#8B92AE",
  nLigthGrey: "#EAECF1",
  nDisableGrey: "#C2C9E1",
  error: "#FF0B71",
  tMagenta: "#E04FC1",
  nGrey: "#DDE0EB",
  sBabyBlue: "#8DB0FF",
  tLightBlue: "#DCE5FF",
  warning: "#FF8A00",
  success: "#2CA638",
  errorLight: "#FFF3FC",
  warningLight: "#FFF1E1",
  successLight: "#F2FFEC",
  nDarkGrey: "#52596F",
  tBabyPink: "#FFE1F7",
};

